// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC8sR9AAygpGEC4Ks58g8lPLpvy7rDnt8',
    appId: '1:1090308097170:web:4efd0fc49d4c3c995cd24b',
    messagingSenderId: '1090308097170',
    projectId: 'riotapp-6955e',
    authDomain: 'riotapp-6955e.firebaseapp.com',
    storageBucket: 'riotapp-6955e.firebasestorage.app',
    measurementId: 'G-2P4T6F9EL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1RcDQw1XrscbLTGQarKy6MnWq15j7CE',
    appId: '1:1090308097170:android:4335b1a9cc44e4755cd24b',
    messagingSenderId: '1090308097170',
    projectId: 'riotapp-6955e',
    storageBucket: 'riotapp-6955e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQp_cic46UyNwDjO9VUXXjLPhWVQSAZE',
    appId: '1:1090308097170:ios:db505aecd59755a65cd24b',
    messagingSenderId: '1090308097170',
    projectId: 'riotapp-6955e',
    storageBucket: 'riotapp-6955e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBQp_cic46UyNwDjO9VUXXjLPhWVQSAZE',
    appId: '1:1090308097170:ios:db505aecd59755a65cd24b',
    messagingSenderId: '1090308097170',
    projectId: 'riotapp-6955e',
    storageBucket: 'riotapp-6955e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC8sR9AAygpGEC4Ks58g8lPLpvy7rDnt8',
    appId: '1:1090308097170:web:880b3f93310ece045cd24b',
    messagingSenderId: '1090308097170',
    projectId: 'riotapp-6955e',
    authDomain: 'riotapp-6955e.firebaseapp.com',
    storageBucket: 'riotapp-6955e.firebasestorage.app',
    measurementId: 'G-MCMH6P1B1N',
  );
}
